association_practice/config/routes.rb
Rails.application.routes.draw do
  
  root 'tweets#index'
  
  devise_for :users
  
  resources :tweets do 
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, onl: [:create, :destroy]
    
  end 
  
  resources :users do 
    resources :relationships, only: [:create, :destroy]
    get 'follows', on: :member
    get 'followers', on: :member
    
  end 
  
end

association_practice/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

association_practice/app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :tweet
  
  
end

association_practice/app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :tweet
  
end

association_practice/app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :following, class_name:"User"
  belongs_to :follower, class_name:"User"
  
end

association_practice/app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user
  has_many :favorites
  has_many :post_comments

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?

  end

end

association_practice/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :favorites
  has_many :favorite_tweets, through: :favorites, source: :tweet
  has_many :post_comments


  #==========自分がフォローしているユーザーとの関連==========
  has_many :active_relationships, class_name:"Relationshhip", foreign_key: :following_id
    #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。
    #なので親はfollowing_id(フォローする側)
  has_many :followings, through: :active_relationships, source: :follower
    #中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを
    #「followings」と定義
  #==========================================================


  #==========自分がフォローされるユーザーとの関連===========
  has_many :passive_relationships, class_name:"Realtionship", foreign_key: :followed_id
    #フォローされる側のUserから見て、フォローしてくるUserを(中間テーブルを介して)集める。
    #なので親はfollower_id(フォローされる側)
  has_many :followers, through: :passive_relationships, source: :following
    #中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを
    #「followers」と定義
  #=========================================================


  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)が、
    #フォローされているユーザー(つまりpassive)の中から、
    #引数に渡されたユーザー(自分)がいるかどうかを調べる
  end

end

association_practice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

association_practice/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    tweet = Tweet.find(params[:tweet_id])
    favorite = current_user.favorites.new(tweet_id: tweet.id)
    favorite.save
    redirect_to tweets_path

  end

  def destroy
    tweet = Tweet.find(params[:tweet_id])
    favorite = current_user.favorites.find_by(tweet_id: tweet.id)
    favorite.destroy
    redirect_to tweets_path

  end
end

association_practice/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = PostComment.new(post_comment_params)
    comment.user_id = current_user.id
    comment.tweet_id = tweet.id
    comment.save
    redirect_to tweet_path(tweet.id)
    
  end 
  
  def destroy
    PostComment.find_by(id: params[:id], tweet_id: params[:tweet_id])
    redirect_to tweet_path(params[:tweet_id])
    
  end
  
  private
  
  def post_comment_params
    params.require(:post_comment).permit(:comment)
    
  end 
  
end

association_practice/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to users_path
    
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
    
  end
end

association_practice/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
    @tweet = Tweet.new #新規投稿用の空のインスタンス

  end


  def create
    tweet = Tweet.new(tweet_params)  #フォームから送られてきたデータ(body)をストロングパラメータを経由して@tweetに代入
    tweet.user_id = current_user.id  #user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインいている自分のid」を代入
    tweet.save
    redirect_to tweets_path

  end



  def index
    @tweets = Tweet.all

  end

  def show
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user
    @post_comment = PostComment.new

  end




  private

  def tweet_params
    params.require(:tweet).permit(:body)  #tweetモデルのカラムのみを許可
  end

end

association_practice/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
    
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @favorite_tweets = @user.favorite_tweets
    
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.followings
    
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.followers
    
  end
  
end

association_practice/app/helpers/application_helper.rb
module ApplicationHelper
end

association_practice/app/helpers/favorites_helper.rb
module FavoritesHelper
end

association_practice/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

association_practice/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

association_practice/app/helpers/tweets_helper.rb
module TweetsHelper
end

association_practice/app/helpers/users_helper.rb
module UsersHelper
end

association_practice/app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

association_practice/app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

association_practice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %> <!--deviseのメソッド（ログインしているかどうかを判断）-->
      <%= link_to '新規投稿', new_tweet_path %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <%= link_to 'マイページ', user_path(current_user.id) %>
    <% else %>
      <%= link_to '新規登録', new_user_registration_path %>
      <%= link_to 'ログイン', new_user_session_path %>
    <% end %>
    <%= link_to 'ツイート一覧', tweets_path %>
    <%= link_to 'ユーザー一覧', users_path %>
    
    <%= yield %>
  </body>
</html>

association_practice/app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

association_practice/app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

association_practice/app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

association_practice/app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<p>Find me in app/views/tweets/index.html.erb</p>

<% @tweets.each do |tweet| %>
  <hr>
  <p>
    <span>email: </span>
    <%= link_to tweet.user.email, user_path(tweet.user.id) %>
  </p>
  <p>
    <span>ツイート内容: </span>
    <%= link_to tweet.body, tweet_path(tweet.id) %><br/>
    <%= link_to "#{tweet.post_comments.count}コメント", tweet_path(tweet.id) %>
  </p>
  <% if user_signed_in? %>
    <% if tweet.favorited_by?(current_user) %> <!--ログインしているユーザーがfavoしたかどうかで分岐-->
      <p>
        <%= link_to tweet_favorites_path(tweet.id), method: :delete do %>
          ❤<%= tweet.favorites.count %>
        <% end %>
      </p>
    <% else %>
      <p>
        <%= link_to tweet_favorites_path(tweet.id), method: :post do %>
          ♡<%= tweet.favorites.count %>
        <% end %>
      </p>
    <% end %>

    <% if current_user != tweet.user %>
      <% if tweet.user.followed_by?(current_user) %>
        <p>
          <%= link_to 'フォロー済み', user_relationships_path(tweet.user.id),
              method: :delete %>
        </p>
      <% else %>
        <p>
          <%= link_to 'フォローする', user_relationships_path(tweet.user.id),
              method: :post %>
        </p>
      <% end %>
    <% end %>
  <% else %>
      <p>
        <span>お気に入り数: </span>
        <%= tweet.favorites.count %>
      </p>

  <% end %>

<% end %>

association_practice/app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

<%= form_with model:@tweet do |f| %>
  <%= f.label :body,"ツイート" %><br/>
  <%= f.text_field :body %><br/>
  <%= f.submit %>
<% end %>

association_practice/app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>

<hr>
<p>
  <span>email: </span>
  <%= @user.email %>
</p>
<p>
  <span>ツイート内容: </span>
  <%= @tweet.body %>
</p>


<h2>コメント一覧</h2>
<p>
  コメント件数: <%= @tweet.post_comments.count %>
</p>
<% @tweet.post_comments.each do |post_comment| %>
  <hr>
  <p>
    <%= post_comment.user.email %> <%= post_comment.comment %>
    <% if current_user != tweet.user %>
      <% if tweet.user.followed_by?(current_user) %>
        <p>
          <%= link_to 'フォロー済み', user_relationships_path(tweet.user.id),
              method: :delete %>
        </p>
      <% else %>
        <p>
          <%= link_to 'フォローする', user_relationships_path(tweet.user.id),
              method: :post %>
        </p>
      <% end %>
    <% end %>
    <% if post_comment.user == current_user %>
      <%= link_to '削除', tweet_post_comment_path(post_comment.tweet, post_comment), method: :delete %>
    <% end %>
  </p>
<% end %>

<h4>コメントをする</h4>
<%= form_with(model:[@tweet, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, row:'3' %>
  <%= f.submit 'コメント' %>
<% end %>

association_practice/app/views/users/followers.html.erb
<h1>User followers</h1>

<% @users.each do |user| %>
  <hr>
  <p>
    <span>email: </span>
    <%= link_to user.email, user_path(user.id) %>
  </p>
  <% if current_user != user %>
    <% if user.followed_by?(current_user) %>
      <p>
        <%= link_to 'フォロー済み', user_relationships_path(user.id), method: :delete %>
      </p>
    <% else %>
      <p>
        <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
      </p>
    <% end %>
  <% end %>
<% end %>

association_practice/app/views/users/follows.html.erb
<h1>User follows</h1>

<% @users.each do |user| %>
  <hr>
  <p>
    <span>email: </span>
    <%= link_to user.email, user_path(user.id) %>
  </p>
  <% if current_user != user %>
    <% if user.followed_by?(current_user %>
      <p>
        <%= link_to 'フォロー済み', user_relationships_path(user.id), method: :delete %>
      </p>
    <% else %>
      <p>
        <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
      </p>
    <% end %>
  <% end %>
<% end %>

association_practice/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @users.each do |user| %>
  <hr>
  <p><span>email: </span><%= link_to user.email, user_path(user.id) %></p>

  <% if current_user != user %>
    <% if user.followed_by?(current_user) %>
      <p>
        <%= link_to 'フォロー済み', user_relationships_path(tweet.user.id),
            method: :delete %>
      </p>
    <% else %>
      <p>
        <%= link_to 'フォローする', user_relationships_path(tweet.user.id),
            method: :post %>
      </p>
    <% end %>
  <% end %>

<% end %>

association_practice/app/views/users/show.html.erb
<h1>Users show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<hr>
<p><span>email: </span><%= @user.email %></p>

<p>
  <%= link_to 'フォロー', follows_user_path(@user.id) %>
</p>
<p>
  <%= link_to 'フォロワー', followers_user_path(@user.id) %>
</p>
<% if current_user != user %>
  <% if @user.followed_by?(current %>
    <p>
      <%= link_to 'フォロー済み', user_relationships_path(@user.id), method: :delete %>
    </p>
  <% else %>
    <p>
      <%= link_to 'フォローする', user_relationships_path(@user.id), method: :post %>
    </p>
  <% end %>
<% end %>

<% @tweets.each do |tweet| %>
  <hr>
  <p><span>ツイート内容: </span><%= link_to tweet.body, tweet_path(tweet.id) %></p>
<% end %>

<h2>いいね❤️された投稿</h2>
<% @favorite_tweets.each do |tweet| %>
  <hr>
  <p>
    <span>❤️内容: </span>
    <%= link_to tweet.body, tweet_path(tweet.id) %>
  </p>
<% end %>